server:
  port: 8201
spring:
  application:
    name: service-hospital
  profiles:
    active: dev
  datasource:
    username: root
    password: wnh
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yygh_hosp?useSSL=false
