server:
  port: 8201
spring:
  application:
    name: service-hospital
  profiles:
    active: dev
  datasource:
    username: root
    password: wnh
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yygh_hosp?characterEncoding=utf-8&useSSL=false
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  data:
    mongodb:
      uri: mongodb://192.168.119.128:27017/yygh_hosp
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848