server:
  port: 10010
spring:
  application:
    name: service-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      routes:
        - id: service-hospital
          uri: lb://service-hospital
          predicates:
            - Path=/*/hosp/**

        - id: service-cmn
          uri: lb://service-cmn
          predicates:
              - Path=/*/cmn/**
