server:
  port: 80
spring:
  application:
    name: service-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      routes:
        - id: service-hospital
          uri: lb://service-hospital
          predicates:
            - Path=/*/hospital/**
        - id: service-cmn
          uri: lb://service-cmn
          predicates:
            - Path=/*/cmn/**
        - id: service-user
          uri: lb://service-user
          predicates:
            - Path=/*/user/**
        - id: service-sms
          uri: lb://service-sms
          predicates:
            - Path=/*/sms/**
