server:
  port: 8204
spring:
  application:
    name: service-sms
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  redis:
    port: 6379
    host: 192.168.119.128
    password: 123456
    timeout: 100000
    lettuce:
      pool:
        max-active: 20
        max-wait: -1
        max-idle: 5
        min-idle: 0
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
